@startuml

actor Client
participant MemberController
participant Member

activate Client

Client -> MemberController : [POST] /members { invalid enum value }
MemberController -> Member : parse data json to entity
Member -> MemberController : Spring validation throws error
MemberController -> Client : return 400 Bad Request

@enduml
